version: '3.3'
services:
  backend:
    image: "444768367/project234-backend:latest"
    ports:
      - "8090:8080"
    volumes:
        - type: bind
          source: ./usr/share/nginx/html/assets
          target: /data
  frontend:
    image: "dto80/project234-frontend:latest"
    ports:
      - "8091:80"

